### ISSUE TITLE
`split` argument with length > 1 for `col_strsplit`

### ISSUE THREAD

**Issue by brodieG** [gaborcsardi/crayon#30]
Another corner case:
```
> col_strsplit(letters[1:2], letters[1:2])
[[1]]
[1] "" ""

[[2]]
[1] "b"

Warning message:
In gregexpr(...) :
  argument 'pattern' has length > 1 and only the first element will be used
> strsplit(letters[1:2], letters[1:2])
[[1]]
[1] ""

[[2]]
[1] ""
```
I suspect almost no-one relies on split args with length > 1, but just making a note of it here in case some day I motivate to fix it.  Unfortunately not _completly_ trivial since `gregexpr` doesn't recycle.

**Comment by gaborcsardi** [comment]
Thanks! Considering that I am planning to rewrite all these in C (and potentially put them in another package, so that crayon does not need compilation), I think giving an error for `length(split) > 1` is good here.

I know it is not the same as `strsplit` then, but until somebody really needs this functionality, that's OK, I guess.
